/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.codecraftr.kata.unusualspending

object App {
    fun hello() = "Goodbye, World!"
}

fun main() = print(App.hello())
